# Generated by Django 5.2.8 on 2025-11-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
    ]
