# Generated by Django 5.2.8 on 2025-11-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_category_tbl_place_tbl_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
