# Generated by Django 5.2.8 on 2025-11-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_place',
            old_name='district_id',
            new_name='district',
        ),
    ]
