# Generated by Django 5.2.8 on 2025-11-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_rename_district_id_tbl_place_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
