# Generated by Django 5.2.8 on 2025-12-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_tbl_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
