# Generated by Django 5.2.8 on 2025-12-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
    ]
