# Generated by Django 5.2.8 on 2025-12-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_remove_tbl_user_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
