# Generated by Django 5.2.8 on 2025-12-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_shop',
            name='shop_status',
            field=models.IntegerField(default=0),
        ),
    ]
