# Generated by Django 5.2.8 on 2025-12-13 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_subcategory'),
        ('Guest', '0006_tbl_shop_shop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delboy_name', models.CharField(max_length=50)),
                ('delboy_email', models.CharField(max_length=50)),
                ('delboy_contact', models.CharField(max_length=50)),
                ('delboy_address', models.CharField(max_length=50)),
                ('delboy_photo', models.FileField(upload_to='Assets/ShopDocs/')),
                ('delboy_proof', models.FileField(upload_to='Assets/ShopDocs/')),
                ('delboy_password', models.CharField(max_length=50)),
                ('delboy_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
