# Generated by Django 5.2.8 on 2025-12-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_deliveryboy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_deliveryboy',
            name='delboy_address',
            field=models.CharField(max_length=150),
        ),
    ]
