# Generated by Django 5.2.8 on 2026-01-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_alter_tbl_deliveryboy_delboy_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_status',
            field=models.IntegerField(default=1),
        ),
    ]
