# Generated by Django 5.2.8 on 2026-03-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_time', models.DateTimeField(auto_now_add=True)),
                ('otp_status', models.IntegerField(default=0)),
            ],
        ),
    ]
