# Generated by Django 5.2.8 on 2025-12-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
