# Generated by Django 5.2.8 on 2025-12-31 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_alter_tbl_deliveryboy_delboy_address'),
        ('User', '0003_delete_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_title', models.CharField(max_length=200)),
                ('com_content', models.TextField()),
                ('com_date', models.DateField(auto_now_add=True)),
                ('com_status', models.IntegerField(default=0)),
                ('com_reply', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
