# Generated by Django 5.2.8 on 2026-01-02 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_alter_tbl_deliveryboy_delboy_address'),
        ('Shop', '0006_tbl_stock'),
        ('User', '0007_tbl_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='com_reply',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.IntegerField(default=0)),
                ('booking_amount', models.IntegerField(null=True)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.IntegerField(default=1)),
                ('cart_status', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product')),
            ],
        ),
    ]
