# Generated by Django 5.2.8 on 2026-01-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_tbl_complaint_com_reply_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.FloatField(null=True),
        ),
    ]
