# Generated by Django 5.2.8 on 2026-01-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_tbl_booking_booking_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
