# Generated by Django 5.2.8 on 2026-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
