# Generated by Django 5.2.8 on 2026-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_tbl_cart_cancel_date_tbl_cart_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
